name = "learn-cannon"
version = "0.0.1"
description = "Cannon learn - Sample Foundry Project"

[deploy.counter]
artifact = "Counter"

[var.main]
number = "420"

[invoke.set_number]
target = ["counter"]
func = "setNumber"
args = ["<%= settings.number %>"]