name = "buy-me-a-coffee-foundry"
version = "0.0.1"
description = "Buy me a coffee - Sample Foundry Project"

[clone.greeter]
source = "greeter:2.11.0"
target = "buy-me-a-coffee-foundry:0.0.1@greeter"

[deploy.Coffee]
artifact = "BuyMeACoffee"
args = ["<%= greeter.Greeter.address %>"]